import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="p-10 text-2xl min-w-full font-semibold">
          Bug Report System (BRS)
          <hr className="mt-2 w-full border-red-700 border-8" />
        </div>
        {children}
      </body>
    </html>
  );
}
